version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    ports:
     - "9200:9200"
     - "9300:9300"

  contentaggregator:
    build: .
    volumes:
     - ./images:/var/images
    links:
     - elasticsearch
    environment:
     - elasticsearch=elasticsearch
