version: '2'
services:
  elasticsearch:
    image: elasticsearch:2
    ports:
     - "9200:9200"
     - "9300:9300"

  contentaggregator:
    image: aretera/foopipes:latest-sdk
    volumes:
     - ./images:/var/images
    ports:
     - 80
    links:
     - elasticsearch
    environment:
     - spaceId=cfexampleapi
     - accessToken=b4c0n73n7fu1