version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    ports:
     - "9200:9200"
     - "9300:9300"

  foopipes:
    image: aretera/foopipes:latest-sdk
    volumes:
     - .:/project
     - ./images:/var/images
    ports:
     - 80
    links:
     - elasticsearch
    environment:
     - elasticsearch=elasticsearch
